project:
  type: website
  output-dir: docs

website:
  title: "Loizos Konstantinou"
  favicon: favicon.ico
  site-url: https://www.loizos.xyz
  repo-url: https://www.loizos.xyz
  repo-branch: quarto
  page-navigation: true
  google-analytics:
    tracking-id: "G-K5PK7P3TJZ"
    anonymize-ip: true
  navbar:
    background: primary
    right:
      - href: blog.qmd
        text: Blog
      - href: software/index.qmd
        text: Projects
      - href: cv.qmd
        text: Resume
      - icon: linkedin
        href: https://www.linkedin.com/in/loizoskon/
      - icon: github
        href: https://github.com/LoizosKo
      - icon: twitter
        href: https://twitter.com/loizoskon
      - icon: medium
        href: https://medium.com/@loizoskon
      - icon: youtube
        href: https://www.youtube.com/@okay.but_why      

  search:
    location: navbar
    type: overlay
format:
  html:
    theme:
      light: solar
    css: styles.css
