<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.269">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Loizos Konstantinou - Titanic Dataset</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../favicon.ico" rel="icon">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>
<script async="" src="https://www.googletagmanager.com/gtag/js?id=G-K5PK7P3TJZ"></script>

<script type="text/javascript">

window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());
gtag('config', 'G-K5PK7P3TJZ', { 'anonymize_ip': true});
</script>

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<link rel="stylesheet" href="../styles.css">
</head>

<body class="nav-fixed fullcontent">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">Loizos Konstantinou</span>
    </a>
  </div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../blog.html">
 <span class="menu-text">Blog</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../software/index.html">
 <span class="menu-text">Projects</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../cv.html">
 <span class="menu-text">About Me</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://www.linkedin.com/in/loizoskon/"><i class="bi bi-linkedin" role="img">
</i> 
 <span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/LoizosKo"><i class="bi bi-github" role="img">
</i> 
 <span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://twitter.com/loizoskon"><i class="bi bi-twitter" role="img">
</i> 
 <span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://medium.com/@loizoskon"><i class="bi bi-medium" role="img">
</i> 
 <span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://www.youtube.com/@okay.but_why"><i class="bi bi-youtube" role="img">
</i> 
 <span class="menu-text"></span></a>
  </li>  
</ul>
              <div id="quarto-search" class="" title="Search"></div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Titanic Dataset</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<p><code>Let's work with the titanic dataset.</code></p>
<p><code>1. Construct a table showing the distribution of passengers by class and survival.</code></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>titanic <span class="sc">%$%</span> <span class="fu">table</span>(survived, pclass)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        pclass
survived   1   2   3
       0 123 158 528
       1 200 119 181</code></pre>
</div>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># magrittr does this --&gt; table(titanic$survived, titanic$pclass)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><code>2. Construct a logistic regression model that links survival to the passenger class. Write out the equation first without Running it in R. HINT: Class is a factor variable</code></p>
<p><span class="math display">\[
log(odds(y)) = β0 + β1*pclass2 + β2*plcass3
\]</span></p>
<p><span class="math display">\[
odds(y) = e^{β_0} * e^{β_1 * pclass2} * e^{β_2 * pclass3}
\]</span></p>
<p>β0 = intercept</p>
<p>y = survival</p>
<p><code>3. Using hand-calculations, determine the coefficients in the model and interpret them (HINT: all you need to do is to use the table, calculate odds for the default category and the odds-ratios for the other categories versus the default)</code></p>
<p><strong>e.g.&nbsp;not survival is the default exercise (i.e.&nbsp;=0). prob of survival of:</strong></p>
<p>first class =&gt; 200/(200+123) = 62% of people survived</p>
<p>second class =&gt; 119/(119+158) = 43% of people survived</p>
<p>third class =&gt; 181/(181+528) = 26% of people survived</p>
<p><strong>Probabilities vary between zero and one. Instead, for the purpose of the logistical regression we can calculate odds of survival of</strong>:</p>
<p>first class =&gt;200/123=1.62 =&gt; for each first class person who died, 1.62 first class people survived.</p>
<p>second class =&gt;119/158 = 0.75 =&gt; for each second class person who died, 0.75 second class person survived.</p>
<p>third class =&gt;181/528 = 0.34 =&gt; for each third class person who died, 0.34 third class person survived.</p>
<p><strong>When we take the log of odds, the result varies from - infinity to + infinity. log of survival of:</strong></p>
<p>first class people: log(200/123)=0.486</p>
<p>second class people: log(119/158)=-0.28</p>
<p>third class people: log(181/528)=-1.07</p>
<p><code>4. Now Run the model in R. Confirm that you got the same results as in part c). Interpret the results and talk about significance (both statistical and substantive).</code></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>titanic <span class="sc">%$%</span> <span class="fu">summary</span>(<span class="fu">glm</span>(survived <span class="sc">~</span> <span class="fu">factor</span>(pclass), <span class="at">family =</span> <span class="st">"binomial"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = survived ~ factor(pclass), family = "binomial")

Deviance Residuals: 
    Min       1Q   Median       3Q      Max  
-1.3896  -0.7678  -0.7678   0.9791   1.6525  

Coefficients:
                Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)       0.4861     0.1146   4.242 2.21e-05 ***
factor(pclass)2  -0.7696     0.1669  -4.611 4.02e-06 ***
factor(pclass)3  -1.5567     0.1433 -10.860  &lt; 2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 1741.0  on 1308  degrees of freedom
Residual deviance: 1613.3  on 1306  degrees of freedom
AIC: 1619.3

Number of Fisher Scoring iterations: 4</code></pre>
</div>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>question2 <span class="ot">&lt;-</span> titanic <span class="sc">%$%</span> <span class="fu">glm</span>(survived <span class="sc">~</span> <span class="fu">factor</span>(pclass), <span class="at">family =</span> <span class="st">"binomial"</span>)</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>(question2<span class="sc">$</span>coefficients)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    (Intercept) factor(pclass)2 factor(pclass)3 
      1.6260163       0.4631962       0.2108239 </code></pre>
</div>
</div>
<p>This code leaves us with the following equation of log odds:</p>
<p>Survived = 0.486 -0.77class2 -1.56class3</p>
<p>The significant p-values are telling us that the intercept is not zero. It means that the beta one (β1) is different from zero. This implies that there is a difference between classes and survival. We do not know yet what is the magnitude of the difference because this is a difference in log odds.</p>
<p>Since is negative it means that classes 2 and 3 have lower survival chances from the first class. The 3rd class has the lowest chances of survival since its β1 coefficient has the highest negative number.</p>
<p><code>5. What's the probability of survival for each class of passengers?</code></p>
<p><strong>First class had the odds of survival of 1.62</strong>. We can calculate the probability of survival as (1.62)/(1 + 1.62) = 0.6183206 or about 61.8%.</p>
<p><strong>Second class had the odds of survival of 0.75</strong>. We can calculate the probability of survival as (0.75)/(1 + 0.75) = 0.4285714 or about 42.8%</p>
<p><strong>Third class had the odds of survival of 0.34</strong>. We can calculate the probability of survival as (0.34)/(1 + 0.34) = 0.2537313 or about 25.3%</p>
<p><code>6. Construct a model that interacts class of passenger and his/her gender. Interpret the results the same way you did before.</code></p>
<p>First we conduct the model just like as before but this time we add gender (aka ‘sex’) as a factor variable. This time though we either add or multiply the one variable with the other. This model would help us make predictions for a passenger.</p>
<p>Because here the model assumes interaction between class and gender we construct the model with a ‘*’ sign. If we add a ‘*’ sign we assume that there are interactions; meaning that the effect of class depends on gender OR the effect of gender depends on class.</p>
<p>—The alternative was the ‘+’ sign. If we add a ‘+’ sign we assume that there are no interactions; meaning that the effect of class does not depend on gender. This was our assumption when we were doing linear models.—</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">glm</span>(survived<span class="sc">~</span><span class="fu">factor</span>(pclass) <span class="sc">*</span> <span class="fu">factor</span>(sex), <span class="at">family =</span> <span class="st">"binomial"</span>, <span class="at">data =</span> titanic))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = survived ~ factor(pclass) * factor(sex), family = "binomial", 
    data = titanic)

Deviance Residuals: 
    Min       1Q   Median       3Q      Max  
-2.5924  -0.5745  -0.5745   0.4902   1.9610  

Coefficients:
                                Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)                       3.3250     0.4549   7.309 2.68e-13 ***
factor(pclass)2                  -1.2666     0.5485  -2.309   0.0209 *  
factor(pclass)3                  -3.3621     0.4748  -7.081 1.43e-12 ***
factor(sex)male                  -3.9848     0.4815  -8.277  &lt; 2e-16 ***
factor(pclass)2:factor(sex)male   0.1617     0.6104   0.265   0.7911    
factor(pclass)3:factor(sex)male   2.3039     0.5158   4.467 7.95e-06 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 1741  on 1308  degrees of freedom
Residual deviance: 1210  on 1303  degrees of freedom
AIC: 1222

Number of Fisher Scoring iterations: 5</code></pre>
</div>
</div>
<p><strong>Let’s make an assumption for a male sitting in first class.</strong></p>
<p>log odds of survival =&gt; 3.325 - 3.9848 = -0.6598</p>
<p>odds of survival =&gt; exp(-0.6598) = 0.5169547</p>
<p>probability of survival =&gt; 0.5169547/(1+0.5169547) = 0.3407845 or 34%</p>
<p><strong>Let’s make an assumption for a male sitting in second class.</strong></p>
<p>log odds of survival =&gt; 3.325 -1.2666 - 3.9848+0.1617 = -1.7647</p>
<p>odds of survival =&gt; exp(-1.7647) = 0.1712382</p>
<p>probability of survival =&gt; 0.1712382/(1+0.1712382) = 0.1462027 or 14.6%</p>
<p><strong>Let’s make an assumption for a male sitting in third class.</strong></p>
<p>log odds of survival =&gt; 3.325 -3.3621 - 3.9848 +2.3039 = -1.718</p>
<p>odds of survival =&gt; exp(-1.718) = 0.1794246</p>
<p>probability of survival =&gt; 0.1794246/(1+0.1794246) = 0.1521289 or 15.21%</p>
<p><strong>Let’s make an assumption for a female sitting in first class.</strong></p>
<p>log odds of survival =&gt; 3.325</p>
<p>odds of survival =&gt; exp(3.325) = 27.799</p>
<p>probability of survival =&gt; 27.799/(1+27.799) = 0.9652766 or 96.5%</p>
<p><strong>Let’s make an assumption for a female sitting in second class.</strong></p>
<p>log odds of survival =&gt; 3.325 -1.2666 = 2.0584</p>
<p>odds of survival =&gt; exp(2.0584) = 7.833426</p>
<p>probability of survival =&gt; 7.833426/(1+7.833426) = 0.8867936 or 88.6%</p>
<p><strong>Let’s make an assumption for a female sitting in third class.</strong></p>
<p>log odds of survival =&gt; 3.325 -3.3621 = -0.0371</p>
<p>odds of survival =&gt; exp(-0.0371) = 0.9635798</p>
<p>probability of survival =&gt; 0.9635798/(1+0.9635798) = 0.4907261 or 49%</p>
<p><u><strong>Interpretation of results</strong></u></p>
<p>It looks like the closer someone is in the first class, the better the chance to survive. However, there is an interesting result between men of third and second category, where the men in third category had slightly higher chances of survival than the men in second class. In general, females had higher chances of survival. Even the females in the third class had 15% higher chance of survival than the males in the first class (49% vs 34%). Around 9 out of 10 women survived in classes 1 and 2. One out of two women survived out of the third class. Only one out of three men in the first class survived while in classes 2 and 3 men had the lowest chances of survival (14.6% and 15.2%). This slight difference though can also be due to random noise.</p>
<p><u>How we arrived to those results</u>:</p>
<p>After running the logistical regression model we come up with the intercept and coefficient number odds which where in log form; hence we had to convert those in actual odds. Before converting them to odds, we sum up the related variables that we want to find in order to also have the log odds of survival (e.g.&nbsp;for female in second class we used the intercept 3.325 and the pclass2 value -1.2666).</p>
<p>Then, we exponentiate the log odds of survival to find the actual odds of survival (e.g.&nbsp;female in second class = 7.83 — which means each female who died, 7.83 survived).</p>
<p>Because human brain is not well designed enough to perceive odds as a measurement, we converted those to probability using the formula:</p>
<p><span class="math display">\[
probability = odds/1+odds
\]</span></p>
<p>We did that for each one of the six outcomes</p>
<ul>
<li><p>male 1st class = 34%</p></li>
<li><p>male 2nd class = 14.6%</p></li>
<li><p>male 3rd class = 15.2%</p></li>
<li><p>female 1st class = 96.5%</p></li>
<li><p>female 2nd class = 88.6%</p></li>
<li><p>female 3rd class = 49%</p></li>
</ul>



</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>