on:
  push:
    branches: quarto
  pull_request:
    branches: quarto
  # to be able to trigger a manual build
  workflow_dispatch:

name: Render and deploy site to Netlify

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Quarto
        uses: quarto-dev/quarto-actions/install-quarto@v1

      # Install any computing dependency you may need, usually either python and Jupyter or R
      # More specific examples will be shared on quarto-dev/quarto-actions project

      - name: Render site
        # Add any command line argument needed
        run: |
          quarto render

      - name: Deploy to Netlify
        id: netlify-deploy
        uses: nwtgck/actions-netlify@v1
        with:
          # The folder the action should deploy. Adapt if you changed in Quarto config
          publish-dir: "./_site"
          production-branch: quarto
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "Deploy from GHA: ${{ github.event.pull_request.title || github.event.head_commit.message }} (${{ github.sha }})"
          enable-pull-request-comment: true #  Comment on pull request
          enable-commit-comment: true # Comment on GitHub commit
          enable-commit-status: true # GitHub commit status
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 1
